config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  resources :lists do
    resources :bookmarks
  end
  resources :bookmarks, only: [:destroy]
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :show, :update]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="card-product">
    <div class="lists">
      <% @lists.each do |list| %>
      <div class="card-product">
          <span class="list-title">
            <%= link_to list.name, list_path(list), class:"btn-click"%>
         </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="page-width">
</div>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= simple_form_for([@list]) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Add List", class: 'btn-submit-movie mt-3' %>
<% end %>
<div>
  <%= link_to "Back to Lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
   <h1><%= @list.name %></h1>
   <div class="card-show-title">
      <h2>Movies</h2>
   </div>
   <div class="row cards-movie">
      <% @list.bookmarks.each do |bookmark| %>
      <div class="col-6-sm">
         <div class="card-movie">
            <h5><%= bookmark.movie.title %></h5>
            <%# <p><%= %>
         </div>
         <% end %>
      </div>
   </div>
</div>
<div class="row">
   <div class="col-12">
      <hr>
      <div class="form">
         <h3>Add a new movie</h3>
         <%= simple_form_for [ @list, @bookmark ] do |f| %>
         <%= f.input :comment, placeholder: 'Add your comment'%>
         <%= f.association :movie %>
         <%= f.submit 'Add movie', class: "btn btn-primary"%>
         <% end %>
      </div>
   </div>
</div>